compile:
	gcc -o fork.o fork.c
	gcc -o zombie.o zombie.c
	gcc -o wait.o wait.c
	gcc -o waitpid.o waitpid.c
	gcc -o signal.o signal.c
	gcc -o echo_client.o echo_client.c
	gcc -o echo_mserver.o echo_mserver.c
